### ISSUE TITLE
stream-deck create Not valid

### ISSUE THREAD

**Issue by hshlss** [stream-deck-for-node/sdk#2]
1、npm i -g @stream-deck-for-node/cli
2、stream-deck create  but it is not valid    stream-deck: command not found

**Comment by hshlss** [comment]
$ npx stream-deck create
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/stream-deck - Not found
npm ERR! 404
npm ERR! 404  'stream-deck@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2022-09-14T07_55_49_931Z-debug.log

**Comment by rustylancet** [comment]
how you fix that？
